const slides = [
{
title:'العنوان', kicker:'مناقشة بحث الماجستير • EMIX • يوليو 2026', notes:'ابدأ بتسمية موضوع البحث والسؤال المركزي. وضّح أن الدراسة تقارن بين نسختين من البيئة نفسها، وأن التغيير الأساسي يقع في سلوك واجهة المستخدم وليس في منطق اللعبة.', html:'<div class="slide-card">\n<div class="title-layout">\n<div>\n<div class="eyebrow">مناقشة أكاديمية عبر الويب</div>\n<h1>أثر واجهات المستخدم التكيفية على معدل احتفاظ اللاعبين في ألعاب الهاتف المحمول</h1>\n<p class="subhead">تقييم واجهة مستخدم تكيفية قائمة على القواعد مقارنة بواجهة تقليدية ثابتة داخل نموذج أولي تفاعلي للعبة هاتف محمول يعمل عبر المتصفح.</p>\n<div class="title-meta">\n<div class="panel"><div class="label">الباحث</div><strong>Mohammed Ali ALOUFI</strong></div>\n<div class="panel"><div class="label">المشرف</div><strong>Mr. Mohammed Al-Nazli</strong></div>\n<div class="panel"><div class="label">البرنامج</div><strong>ماجستير تنفيذي في تصميم واجهة وتجربة المستخدم وتقنيات الألعاب (EMIX)</strong></div>\n<div class="panel"><div class="label">الجهة</div><strong>أكاديمية أنس للفنون</strong></div>\n</div>\n</div>\n<div class="panel soft stack center">\n<div class="phone">\n<div class="status"><span>5G 100%</span><span>09:41</span></div>\n<div class="screen-top"><span>واجهة تكيفية</span><span>00:50</span></div>\n<div class="arena"><div class="player"></div><div class="target"></div></div>\n<div class="tip">تلميح مختصر عند الحاجة</div>\n<div class="controls-row"><div class="control">↗<br/>حركة</div><div class="control highlight">↑<br/>قفز</div></div>\n</div>\n<div class="source-note">تمثيل بصري مبسط للنموذج الأولي الوارد في البحث.</div>\n</div>\n</div>\n<div class="slide-footer"><span>المصدر: صفحة العنوان والملخص</span><span class="section-number">01</span></div>\n</div>'
},
{
title:'سؤال البحث', kicker:'السؤال الذي ينظم الدراسة', notes:'اذكر سؤال البحث كما ورد في الرسالة. ثم وضّح أن الدراسة تستخدم مؤشرات أداء وقابلية استخدام ونية الاستمرار، لأن التجربة تمت في جلسة واحدة.', html:'<div class="slide-card">\n<div class="section-head"><div><div class="eyebrow">01 • الإطار العام</div><h2>سؤال واحد يقود الدراسة</h2></div><span class="pill">سؤال البحث</span></div>\n<div class="callout"><p class="quote">«ما أثر استخدام واجهات المستخدم التكيفية (AUIs) على معدل احتفاظ اللاعبين في ألعاب الهاتف المحمول؟»</p></div>\n<div class="grid-3">\n<div class="panel"><div class="label">المتغير المستقل</div><h3>نوع واجهة المستخدم</h3><p class="muted">واجهة تقليدية ثابتة مقابل واجهة تكيفية قائمة على القواعد.</p></div>\n<div class="panel"><div class="label">مؤشرات الأداء</div><h3>أدلة التفاعل</h3><p class="muted">زمن المهمة، الأخطاء، النقرات غير الصحيحة، وعدد مرات تفعيل التكيف، ومؤشر الأداء النهائي.</p></div>\n<div class="panel good"><div class="label">مؤشر الاحتفاظ</div><h3>نية الاستمرار</h3><p class="muted">استخدمت كمؤشر للاحتفاظ بسبب اعتماد الدراسة على جلسة تجريبية واحدة.</p></div>\n</div>\n<div class="slide-footer"><span>المصدر: ص 3–4، 10، 14–15</span><span class="section-number">02</span></div>\n</div>'
},
{
title:'مشكلة البحث', kicker:'لماذا قد تصبح الواجهة الثابتة عائقًا؟', notes:'وضّح المفارقة: اللاعب المبتدئ قد يواجه عبئًا معرفيًا أعلى، بينما قد يجد اللاعب ذو الخبرة الواجهة أقل مرونة من احتياجاته. المشكلة العملية التي يناقشها البحث هي التسرب المبكر.', html:'<div class="slide-card">\n<div class="section-head"><div><div class="eyebrow">02 • المشكلة</div><h2>واجهة واحدة لا تناسب جميع اللاعبين</h2></div><span class="pill">التسرب المبكر</span></div>\n<div class="grid-2">\n<div class="stack">\n<div class="panel warn"><div class="label">اللاعب المبتدئ</div><h3>معلومات أكثر مما يحتاج</h3><p class="muted">واجهة ثابتة وكثيفة قد ترفع العبء المعرفي وتزيد صعوبة التفاعل واحتمال ارتكاب الأخطاء أو الانقطاع المبكر.</p></div>\n<div class="panel"><div class="label">اللاعب ذو الخبرة</div><h3>مرونة أقل</h3><p class="muted">قد لا تقدم الواجهة الثابتة مستوى كافيًا من التكيف أو المرونة، بما قد يضعف الدافعية للاستمرار.</p></div>\n</div>\n<div class="center">\n<div class="stack" style="width:min(520px,100%)">\n<div class="panel soft"><div class="rule-line"><span class="rule-dot"></span><strong>واجهة واحدة للجميع</strong></div><p class="muted">الحجم والموقع ثابتان • لا توجد مساعدة تكيفية</p></div>\n<div class="center muted">↓</div>\n<div class="panel"><div class="rule-line"><span class="rule-dot"></span><strong>حالات لاعبين مختلفة</strong></div><p class="muted">خبرة • مهارة • سرعة تعلم • أنماط تفاعل مختلفة</p></div>\n<div class="center muted">↓</div>\n<div class="panel warn"><div class="rule-line"><span class="rule-dot"></span><strong>احتمال التسرب المبكر</strong></div><p class="muted">الدراسة تختبر هل يمكن للواجهة التكيفية تقليل هذه الحواجز.</p></div>\n</div>\n</div>\n</div>\n<div class="slide-footer"><span>المصدر: ص 2–3</span><span class="section-number">03</span></div>\n</div>'
},
{
title:'منطق الدراسة', kicker:'المشكلة ← النظرية ← التدخل ← التقييم', notes:'استخدم هذه الشريحة لتوضيح قصة البحث أمام اللجنة: مشكلة التسرب والواجهة الثابتة، ثم الأساس النظري، ثم محرك التكيف القائم على القواعد، ثم التقييم والمقارنة.', html:'<div class="slide-card">\n<div class="eyebrow">03 • منطق الدراسة</div>\n<h2>سلسلة بحث قابلة للاختبار</h2>\n<div class="flow">\n<div class="flow-box"><b>المشكلة</b><div class="muted">التسرب المبكر + واجهة ثابتة</div></div><div class="flow-arrow">←</div>\n<div class="flow-box"><b>الأساس النظري</b><div class="muted">العبء المعرفي + التدفق</div></div><div class="flow-arrow">←</div>\n<div class="flow-box"><b>التدخل</b><div class="muted">واجهة تكيفية قائمة على القواعد</div></div>\n</div>\n<div class="flow">\n<div class="flow-box"><b>القياس</b><div class="muted">زمن المهمة + الأخطاء + التكيف + نية الاستمرار</div></div><div class="flow-arrow">←</div>\n<div class="flow-box"><b>المقارنة</b><div class="muted">ثابتة مقابل تكيفية</div></div><div class="flow-arrow">←</div>\n<div class="flow-box soft"><b>الخلاصة</b><div class="muted">تحسن اتجاهي في مؤشرات تجربة الاستخدام</div></div>\n</div>\n<div class="callout"><p class="muted">تم الإبقاء على آلية اللعب ومهام التجربة ثابتة، بحيث يكون الاختلاف الأساسي في الواجهة واستجابتها لأداء اللاعب.</p></div>\n<div class="slide-footer"><span>المصدر: ص 8–10، 14–15</span><span class="section-number">04</span></div>\n</div>'
},
{
title:'الأساس النظري', kicker:'نظرية العبء المعرفي + نظرية التدفق', notes:'اشرح النظريتين ثم اربطهما مباشرة بالتدخل: تقليل الجهد غير الضروري عبر تبسيط الواجهة والمساعدة عند الحاجة، ودعم توازن التحدي والمهارة من خلال استجابة الواجهة لأداء اللاعب.', html:'<div class="slide-card">\n<div class="section-head"><div><div class="eyebrow">04 • الأساس النظري</div><h2>عدستان تفسران فائدة التكيف</h2></div><span class="pill">CLT + Flow</span></div>\n<div class="grid-2">\n<div class="panel soft"><div class="label">نظرية العبء المعرفي</div><h3>تقليل العبء المعرفي الدخيل</h3><p class="muted" style="margin-top:8px">زيادة المعلومات أو التعقيد غير الضروري قد تستهلك قدرة الذاكرة العاملة وتشتت اللاعب عن المهمة الأساسية.</p><div class="tag-row" style="margin-top:15px"><span class="tag">تبسيط</span><span class="tag">إبراز المهم</span><span class="tag">مساعدة عند الحاجة</span></div></div>\n<div class="panel"><div class="label">نظرية التدفق</div><h3>دعم توازن التحدي والمهارة</h3><p class="muted" style="margin-top:8px">إذا تجاوز التحدي قدرة اللاعب قد يظهر الإحباط، وإذا انخفض كثيرًا قد يظهر الملل. التكيف يدعم تجربة أكثر استجابة.</p><div class="tag-row" style="margin-top:15px"><span class="tag">دعم استجابي</span><span class="tag">مساعدة سياقية</span><span class="tag">تقليل تدريجي</span></div></div>\n</div>\n<div class="panel"><div class="label">النتيجة التصميمية</div><h3>التكيف في الواجهة وليس في منطق اللعبة</h3><p class="muted">النموذج يغير عناصر واجهة المستخدم وفق الأداء، مع الحفاظ على آلية اللعب الأساسية ثابتة.</p></div>\n<div class="slide-footer"><span>المصدر: ص 8–10</span><span class="section-number">05</span></div>\n</div>'
},
{
title:'الدراسات السابقة', kicker:'ماذا قالت الأدبيات قبل هذه الدراسة؟', notes:'قدّم الدراسات الخمس باختصار، ثم انتقل إلى أن الأدبيات تدعم التخصيص والتكيف، لكن الدراسة الحالية تركز مباشرة على عناصر واجهة المستخدم نفسها باستخدام قواعد بسيطة قابلة للتطبيق.', html:'<div class="slide-card">\n<div class="section-head"><div><div class="eyebrow">05 • الدراسات السابقة</div><h2>الأدبيات تدعم التكيف من زوايا متعددة</h2></div><span class="pill">5 دراسات بارزة</span></div>\n<div class="grid-3">\n<div class="panel"><h3>Putkonen (2022)</h3><p class="muted">سلوك اللاعب المبكر كمؤشر للتنبؤ بالاحتفاظ في ألعاب الهاتف المجانية.</p></div>\n<div class="panel"><h3>Tondello (2019)</h3><p class="muted">التخصيص الديناميكي للأنظمة التفاعلية وفق أنواع اللاعبين.</p></div>\n<div class="panel"><h3>Padte (2019)</h3><p class="muted">أثر التغذية الراجعة النصية التكيفية على التفاعل والاستمرار.</p></div>\n<div class="panel"><h3>Makris (2016)</h3><p class="muted">التحديات التقنية لتطبيق الواجهات التكيفية وقت التشغيل.</p></div>\n<div class="panel"><h3>Chen et al. (2021)</h3><p class="muted">استخدام بيانات الأداء للتنبؤ بالانسحاب وتخصيص تجربة اللعب.</p></div>\n<div class="panel soft"><div class="label">المشترك</div><h3>التكيف واعد</h3><p class="muted">الدراسة الحالية تنقل الفكرة إلى تدخل مباشر داخل واجهة لعبة هاتف محمول باستخدام قواعد تفاعلية واضحة.</p></div>\n</div>\n<div class="slide-footer"><span>المصدر: ص 11 وقائمة المراجع</span><span class="section-number">06</span></div>\n</div>'
},
{
title:'الفجوة البحثية', kicker:'المفقود هو الواجهة نفسها', notes:'شدّد على الفجوة كما صيغت في البحث: دراسات سابقة ركزت على سلوك اللاعب أو التنبؤ بالاحتفاظ أو التخصيص العام، بينما تركز الدراسة الحالية مباشرة على تكييف عناصر الواجهة نفسها.', html:'<div class="slide-card">\n<div class="eyebrow">06 • الفجوة البحثية</div>\n<h2>الدراسة تضع واجهة المستخدم في مركز التدخل</h2>\n<div class="grid-2">\n<div class="panel"><div class="label">تركيز سابق</div><div class="bullet-list" style="margin-top:12px"><div class="bullet">تحليل سلوك اللاعبين</div><div class="bullet">التنبؤ بالاحتفاظ</div><div class="bullet">التخصيص العام لتجربة اللعب</div></div></div>\n<div class="panel good"><div class="label">الدراسة الحالية</div><div class="bullet-list" style="margin-top:12px"><div class="bullet">تكييف عناصر الواجهة مباشرة</div><div class="bullet">قواعد إذا–فإن واضحة</div><div class="bullet">مقارنة تكيفية مقابل ثابتة</div><div class="bullet">تقييم قابلية الاستخدام والأداء</div></div></div>\n</div>\n<div class="callout"><p class="quote">الإضافة العملية: أسلوب تكيف قائم على القواعد، واضح وقابل لإعادة التنفيذ، لتغيير الواجهة وفق أداء اللاعب.</p></div>\n<div class="slide-footer"><span>المصدر: ص 11–12</span><span class="section-number">07</span></div>\n</div>'
},
{
title:'المنهجية', kicker:'تصميم شبه تجريبي', notes:'عرّف المتغير المستقل والمتغيرات التابعة، ثم وضّح أن النسختين متطابقتان في محتوى اللعبة ومهامها، وأن الاختلاف الأساسي هو نوع الواجهة واستجابتها للأداء.', html:'<div class="slide-card">\n<div class="section-head"><div><div class="eyebrow">07 • المنهجية</div><h2>مقارنة شبه تجريبية داخل النموذج نفسه</h2></div><span class="pill">مقارنة مضبوطة</span></div>\n<div class="grid-2">\n<div class="stack">\n<div class="panel soft"><div class="label">المتغير المستقل</div><h3>نوع واجهة المستخدم</h3><p class="muted">واجهة تقليدية ثابتة مقابل واجهة تكيفية قائمة على القواعد.</p></div>\n<div class="panel"><div class="label">المتغيرات التابعة / المؤشرات</div><h3>الأداء + قابلية الاستخدام + نية الاستمرار</h3><p class="muted">زمن المهمة، الأخطاء، تفعيل التكيف، التقييم الإرشادي، ونية الاستمرار.</p></div>\n</div>\n<div class="panel center"><div class="choice" style="width:100%">\n<div class="side static"><h3>النسخة A</h3><p class="muted">واجهة تقليدية ثابتة</p><div class="tag-row" style="margin-top:14px"><span class="tag">حجم ثابت</span><span class="tag">موضع ثابت</span><span class="tag">لا تلميحات تكيفية</span></div></div>\n<div class="side adaptive"><h3>النسخة B</h3><p class="muted">واجهة تكيفية</p><div class="tag-row" style="margin-top:14px"><span class="tag">مراقبة الأداء</span><span class="tag">مساعدة سياقية</span><span class="tag">تعديلات على الواجهة</span></div></div>\n</div></div>\n</div>\n<div class="slide-footer"><span>المصدر: ص 14–15</span><span class="section-number">08</span></div>\n</div>'
},
{
title:'العينة', kicker:'عينة قصدية من المختصين', notes:'العينة في الملخص هي ثمانية خبراء من مجالات UI/UX وتطوير الألعاب، من معسكر التقنيات الناشئة والعوالم الافتراضية بأكاديمية طويق. وضّح أن جميع المشاركين استخدموا النسختين وفق إجراءات موحدة.', html:'<div class="slide-card">\n<div class="eyebrow">08 • المشاركون</div>\n<div class="grid-2">\n<div class="panel soft center" style="min-height:270px"><div><div class="big-num">8</div><div class="label" style="margin-top:9px">مشاركون</div><p class="muted" style="margin-top:9px">مختصون في UI/UX وتطوير الألعاب</p></div></div>\n<div class="stack">\n<div class="panel"><div class="label">أسلوب الاختيار</div><h3>العينة القصدية</h3><p class="muted">اختيار مشاركين ذوي خبرة مناسبة لتقييم جودة النموذج وفاعلية التكيف.</p></div>\n<div class="panel"><div class="label">السياق</div><h3>أكاديمية طويق</h3><p class="muted">معسكر التقنيات الناشئة والعوالم الافتراضية في المملكة العربية السعودية.</p></div>\n<div class="panel"><div class="label">المقارنة</div><h3>استخدام النسختين</h3><p class="muted">استخدم جميع المشاركين النسخة التقليدية والنسخة التكيفية وفق إجراءات موحدة.</p></div>\n</div>\n</div>\n<div class="slide-footer"><span>المصدر: ص 2، 15</span><span class="section-number">09</span></div>\n</div>'
},
{
title:'النموذج الأولي', kicker:'لعبة ويب بواجهتين مختلفتين', notes:'تحدث عن الشاشات الرئيسة: البداية، اختيار نمط التجربة، اللعب، تقرير الأداء، ورسائل الإرشاد. الصور هنا تمثيل مبسط مستند إلى الأشكال المضمنة في البحث وليست إعادة تصدير حرفية لها.', html:'<div class="slide-card">\n<div class="section-head"><div><div class="eyebrow">09 • النموذج الأولي</div><h2>بيئة التجربة نفسها — وسلوك واجهة مختلف</h2></div><span class="pill">HTML • CSS • JavaScript</span></div>\n<div class="grid-3">\n<div class="panel center stack"><div class="phone"><div class="status"><span>5G</span><span>09:41</span></div><div class="screen-top"><span>اختبار A/B</span><span>01</span></div><div class="panel" style="padding:8px;background:#121830"><div class="control" style="margin-bottom:7px">النسخة A — ثابتة</div><div class="control highlight">النسخة B — تكيفية</div></div></div><div class="source-note">شاشة اختيار النسخة — إعادة بناء مبسطة للشكل (3-1).</div></div>\n<div class="panel center stack"><div class="phone"><div class="status"><span>5G</span><span>09:41</span></div><div class="screen-top"><span>واجهة ثابتة</span><span>00:40</span></div><div class="arena"><div class="player"></div><div class="target"></div></div><div class="controls-row"><div class="control">⚡<br/>تسريع</div><div class="control">↑<br/>قفز</div></div></div><div class="source-note">الواجهة التقليدية — إعادة بناء مبسطة للشكل (3-2).</div></div>\n<div class="panel center stack"><div class="phone"><div class="status"><span>5G</span><span>09:41</span></div><div class="screen-top"><span>واجهة تكيفية</span><span>00:50</span></div><div class="arena"><div class="player"></div><div class="target"></div></div><div class="tip">تلميح قصير عند الحاجة</div><div class="controls-row"><div class="control">⚡<br/>تسريع</div><div class="control highlight">↑<br/>قفز</div></div></div><div class="source-note">الواجهة التكيفية — إعادة بناء مبسطة للشكل (3-3).</div></div>\n</div>\n<div class="slide-footer"><span>المصدر البصري: ص 16–18</span><span class="section-number">10</span></div>\n</div>'
},
{
title:'المقارنة', kicker:'ثابتة مقابل تكيفية', notes:'أكّد على عدالة المقارنة: الواجهة التقليدية ثابتة، بينما التكيفية تراقب أداء اللاعب وتغيّر عناصر محددة عند تحقق الشروط. المحتوى الأساسي وآلية اللعب لا يتغيران.', html:'<div class="slide-card">\n<div class="eyebrow">10 • التدخل</div><h2>الاختلاف في الواجهة وليس في اللعبة</h2>\n<table class="matrix">\n<thead><tr><th>البعد</th><th>الواجهة التقليدية</th><th>الواجهة التكيفية</th></tr></thead>\n<tbody>\n<tr><td>الحجم / الموضع</td><td>ثابتان</td><td>يمكن تعديلهما وفق القواعد</td></tr>\n<tr><td>الإرشاد</td><td>لا توجد تلميحات تكيفية</td><td>تلميحات قصيرة وسياقية</td></tr>\n<tr><td>الكثافة البصرية</td><td>ثابتة</td><td>يمكن تقليل العناصر غير الضرورية</td></tr>\n<tr><td>الاستجابة للأخطاء</td><td>لا توجد استجابة تكيفية</td><td>إبراز عناصر مهمة عند الحاجة</td></tr>\n<tr><td>آلية اللعب الأساسية</td><td colspan="2"><strong>ثابتة في النسختين</strong></td></tr>\n</tbody></table>\n<div class="callout"><p class="muted">الهدف هو عزل أثر تصميم واجهة المستخدم وآلية استجابتها عن اختلاف محتوى اللعبة أو منطقها.</p></div>\n<div class="slide-footer"><span>المصدر: ص 17–18، 25–26</span><span class="section-number">11</span></div>\n</div>'
},
{
title:'محرك التكيف القائم على القواعد', kicker:'Rule-Based Adaptive Engine', notes:'هذه نقطة مهمة في المناقشة: الرسالة تنص على أن المحرك لا يستخدم الذكاء الاصطناعي أو التعلم الآلي، بل قواعد منطقية إذا–فإن محددة مسبقًا.', html:'<div class="slide-card">\n<div class="section-head"><div><div class="eyebrow">11 • آلية التكيف</div><h2>مؤشرات الأداء ← قواعد واضحة ← استجابة في الواجهة</h2></div><span class="pill">Rule-Based Adaptive Engine</span></div>\n<div class="flow">\n<div class="flow-box"><b>مراقبة</b><div class="muted">الأخطاء • زمن التفاعل • النقرات غير الصحيحة</div></div><div class="flow-arrow">←</div>\n<div class="flow-box"><b>تحليل</b><div class="muted">مقارنة المؤشرات مع شروط معرفة مسبقًا</div></div><div class="flow-arrow">←</div>\n<div class="flow-box"><b>تكيف</b><div class="muted">تعديل عناصر مختارة من الواجهة</div></div>\n</div>\n<div class="grid-4">\n<div class="panel soft"><div class="label">القاعدة 01</div><h3>تكرار الأخطاء</h3><p class="muted">تكبير عنصر تحكم مهم.</p></div>\n<div class="panel"><div class="label">القاعدة 02</div><h3>انخفاض الأداء</h3><p class="muted">إظهار تلميح مختصر.</p></div>\n<div class="panel"><div class="label">القاعدة 03</div><h3>زيادة الحمل البصري</h3><p class="muted">تقليل العناصر غير الضرورية.</p></div>\n<div class="panel good"><div class="label">القاعدة 04</div><h3>تحسن الأداء</h3><p class="muted">إعادة الواجهة تدريجيًا إلى حالتها الطبيعية.</p></div>\n</div>\n<div class="callout"><p class="quote">مهم: آلية اتخاذ القرار قابلة للتفسير وإعادة التنفيذ لأنها مبنية على قواعد إذا–فإن محددة.</p></div>\n<div class="slide-footer"><span>المصدر: ص 19</span><span class="section-number">12</span></div>\n</div>'
},
{
title:'مؤشرات التقييم', kicker:'ماذا يسجل النموذج أثناء اللعب؟', notes:'استعرض المؤشرات الخمسة كما وردت: الأخطاء، النقرات غير الصحيحة، زمن إكمال المهمة، مرات تفعيل قواعد التكيف، ومؤشر الأداء العام. وأضف التقييم الإرشادي ونية الاستمرار كطبقات تقييم أخرى.', html:'<div class="slide-card">\n<div class="eyebrow">12 • التقييم</div><h2>تسجيل الأداء يتم تلقائيًا</h2>\n<div class="metric-grid">\n<div class="metric"><strong>الأخطاء</strong><span>عدد الأخطاء التي ارتكبها اللاعب أثناء اللعب.</span></div>\n<div class="metric"><strong>النقرات غير الصحيحة</strong><span>Misclicks المسجلة داخل النموذج.</span></div>\n<div class="metric"><strong>زمن المهمة</strong><span>الزمن المطلوب لإكمال المهمة.</span></div>\n<div class="metric"><strong>مرات التكيف</strong><span>عدد مرات تفعيل قواعد التكيف.</span></div>\n<div class="metric"><strong>الأداء العام</strong><span>مؤشر الأداء المعروض في التقرير النهائي.</span></div>\n</div>\n<div class="grid-3">\n<div class="panel"><div class="label">قابلية الاستخدام</div><h3>اختبارات الاستخدام</h3><p class="muted">مؤشرات أداء مرتبطة بالتفاعل مع النموذج.</p></div>\n<div class="panel"><div class="label">مراجعة الخبراء</div><h3>التقييم الإرشادي</h3><p class="muted">تحديد نقاط القوة والقصور في النموذج.</p></div>\n<div class="panel soft"><div class="label">الاحتفاظ</div><h3>نية الاستمرار</h3><p class="muted">مؤشر مستخدم للاحتفاظ في دراسة الجلسة الواحدة.</p></div>\n</div>\n<div class="slide-footer"><span>المصدر: ص 10، 20، 23، 26</span><span class="section-number">13</span></div>\n</div>'
},
{
title:'معمارية النظام', kicker:'دورة تكيف مستمرة', notes:'اتبع المسار: تفاعل اللاعب، ثم مراقبة الأداء، ثم محرك القواعد، ثم مدير الواجهة التكيفية، ثم تعديل الواجهة، ثم استمرار اللعب وعودة الدورة من جديد.', html:'<div class="slide-card">\n<div class="section-head"><div><div class="eyebrow">13 • المعمارية</div><h2>الواجهة التكيفية تعمل كحلقة استجابة مستمرة</h2></div><span class="pill">System Architecture</span></div>\n<div class="arch">\n<div class="arch-col"><div class="arch-box"><strong>تفاعل اللاعب</strong><span class="muted">أحداث واجهة اللعبة</span></div><div class="connector">↓</div><div class="arch-box"><strong>مراقبة الأداء</strong><span class="muted">جمع وتحليل السلوك</span></div></div>\n<div class="arch-col"><div class="arch-box soft"><strong>محرك القواعد</strong><span class="muted">مقارنة المؤشرات مع الشروط المعرفة مسبقًا</span></div><div class="connector">↓</div><div class="arch-box good"><strong>مدير الواجهة التكيفية</strong><span class="muted">تطبيق تعديلات الواجهة</span></div></div>\n<div class="arch-col"><div class="arch-box"><strong>استجابة الواجهة</strong><span class="muted">تكبير عناصر • تلميحات • تقليل عناصر</span></div><div class="connector">↺</div><div class="arch-box"><strong>استمرار اللعب</strong><span class="muted">مراقبة الحالة التالية</span></div></div>\n</div>\n<div class="callout"><p class="muted">التعديلات تقع في طبقة الواجهة، بينما يظل منطق اللعب الأساسي ثابتًا.</p></div>\n<div class="slide-footer"><span>المصدر البصري: ص 21، الشكل (3-6)</span><span class="section-number">14</span></div>\n</div>'
},
{
title:'إجراءات التنفيذ', kicker:'من مراجعة الأدبيات إلى تحليل النتائج', notes:'لخص الخطوات الثماني بسرعة، ثم ركّز على التجربة الموحدة: اختيار النسخة، تنفيذ المهمة، تسجيل المؤشرات، تطبيق التكيف عند تحقق الشروط، ثم إصدار التقرير النهائي.', html:'<div class="slide-card">\n<div class="eyebrow">14 • الإجراءات</div><h2>سلسلة تنفيذ قابلة للتكرار</h2>\n<div class="timeline">\n<div class="step"><b>01</b>مراجعة الأدبيات</div><div class="step"><b>02</b>بناء النموذج</div><div class="step"><b>03</b>تطوير النسختين</div><div class="step"><b>04</b>تصميم القواعد</div><div class="step"><b>05</b>اختبار الوظائف</div><div class="step"><b>06</b>تنفيذ التجربة</div><div class="step"><b>07</b>تسجيل المؤشرات</div><div class="step"><b>08</b>التحليل والاستنتاج</div>\n</div>\n<div class="grid-2">\n<div class="panel"><div class="label">ضبط التجربة</div><h3>بيئة لعب موحدة</h3><p class="muted">استخدام الجهاز نفسه أو أجهزة متقاربة، مع ثبات المهمة وعناصر اللعب الأساسية.</p></div>\n<div class="panel soft"><div class="label">الدورة التكيفية</div><h3>قياس ← قاعدة ← تغيير ← قياس</h3><p class="muted">في النسخة التكيفية تتغير الواجهة عند تحقق شروط محددة مسبقًا.</p></div>\n</div>\n<div class="slide-footer"><span>المصدر: ص 22–23</span><span class="section-number">15</span></div>\n</div>'
},
{
title:'النتائج', kicker:'ماذا أظهر التقييم الوظيفي؟', notes:'كن دقيقًا: البحث يذكر تحسنًا واضحًا في الواجهة التكيفية وانخفاضًا في معدلات الأخطاء وزمن إكمال المهمة، لكنه لا يقدم في نص النتائج القيم الرقمية اللازمة لبناء نسب أو أعمدة رقمية. لذلك نعرض النتائج اتجاهيًا فقط.', html:'<div class="slide-card">\n<div class="section-head"><div><div class="eyebrow">15 • النتائج</div><h2>النسخة التكيفية أظهرت أداءً أفضل في المؤشرات الأساسية</h2></div><span class="pill">بدون أرقام مخترعة</span></div>\n<div class="result-lane">\n<div class="result-card static"><div class="result-head"><h3>الواجهة التقليدية</h3><span class="status-badge bad">حالة مرجعية</span></div>\n<div class="result-point">العناصر تبقى ثابتة طوال التجربة.</div><div class="result-point">لا توجد تلميحات أو استجابة تكيفية للأداء.</div><div class="result-point">تمثل خط الأساس للمقارنة.</div></div>\n<div class="result-card adaptive"><div class="result-head"><h3>الواجهة التكيفية</h3><span class="status-badge good">تحسن اتجاهي</span></div>\n<div class="result-point">انخفاض مُبلغ عنه في معدلات الأخطاء.</div><div class="result-point">انخفاض مُبلغ عنه في زمن إكمال المهمة.</div><div class="result-point">تجربة أكثر مرونة واستجابة لاحتياجات اللاعب.</div></div>\n</div>\n<div class="panel soft"><div class="label">النتيجة الوظيفية</div><h3>نجح النموذج في تنفيذ قواعد التكيف مع المحافظة على آلية اللعب الأساسية.</h3><p class="muted" style="margin-top:7px">وهذا دعم تقييم أثر الواجهة باعتبارها العامل المتغير الرئيس.</p></div>\n<div class="slide-footer"><span>المصدر: ص 2، 25–27</span><span class="section-number">16</span></div>\n</div>'
},
{
title:'المناقشة', kicker:'لماذا تتسق النتيجة مع الإطار النظري؟', notes:'اربط ما حدث بالفعل بالأساس النظري: تبسيط العرض والتوجيه المناسب عند الحاجة يتسقان مع تقليل العبء المعرفي، والاستجابة للأداء تتسق مع دعم التدفق. كما يذكر البحث توافق النتيجة مع اتجاهات الدراسات السابقة.', html:'<div class="slide-card">\n<div class="eyebrow">16 • المناقشة</div><h2>النتيجة تتسق مع منطق الإطار النظري</h2>\n<div class="grid-3">\n<div class="panel soft"><div class="label">العبء المعرفي</div><h3>تقليل الاحتكاك غير الضروري</h3><p class="muted">تبسيط العرض وإظهار المساعدة المناسبة يمكن أن يقلل الجهد المطلوب من اللاعب للتعامل مع الواجهة.</p></div>\n<div class="panel"><div class="label">التدفق</div><h3>دعم أكثر استجابة</h3><p class="muted">يمكن للواجهة دعم اللاعب عند انخفاض الأداء وتقليل المساعدة عند تحسنه.</p></div>\n<div class="panel good"><div class="label">الدراسات السابقة</div><h3>اتجاه متسق</h3><p class="muted">الرسالة تشير إلى توافق النتيجة مع الأدبيات التي تؤكد التخصيص والاستجابة لسلوك المستخدم.</p></div>\n</div>\n<div class="callout"><p class="quote">الإضافة ليست «تكيفًا بالذكاء الاصطناعي»، بل حلقة تكيف واضحة وقابلة للتفسير مبنية على قواعد صريحة.</p></div>\n<div class="slide-footer"><span>المصدر: ص 26–27</span><span class="section-number">17</span></div>\n</div>'
},
{
title:'مساهمة الدراسة', kicker:'ماذا أنجز البحث فعليًا؟', notes:'افصل ما ثبت في الدراسة عن الأفكار المستقبلية. المساهمة المثبتة: نموذج أولي عامل، محرك تكيف قائم على القواعد، ثبات آلية اللعب، وتحسن اتجاهي في النتائج المرتبطة بقابلية الاستخدام.', html:'<div class="slide-card">\n<div class="section-head"><div><div class="eyebrow">17 • المساهمة</div><h2>من سؤال بحث إلى نمط تصميم عملي</h2></div><span class="pill">الإنجاز الفعلي</span></div>\n<div class="grid-3">\n<div class="panel"><div class="big-num">01</div><div class="label" style="margin-top:8px">النموذج</div><p class="muted">نموذج أولي للعبة هاتف محمول عبر المتصفح بنسختين للواجهة.</p></div>\n<div class="panel soft"><div class="big-num">02</div><div class="label" style="margin-top:8px">المحرك</div><p class="muted">قواعد إذا–فإن تحول أداء اللاعب إلى تعديلات على الواجهة.</p></div>\n<div class="panel good"><div class="big-num">03</div><div class="label" style="margin-top:8px">الدليل</div><p class="muted">تشغيل وظيفي ونتائج اتجاهية أفضل للواجهة التكيفية في مؤشرات تجربة الاستخدام.</p></div>\n</div>\n<div class="panel"><div class="label">الخلاصة التصميمية</div><h3>كيّف الواجهة قبل أن تغيّر اللعبة.</h3><p class="muted">البحث يقدّم الواجهة المستجيبة للسلوك كاتجاه عملي لتحسين قابلية الاستخدام واستمرارية التفاعل.</p></div>\n<div class="slide-footer"><span>المصدر: ص 28، 30–31</span><span class="section-number">18</span></div>\n</div>'
},
{
title:'حدود الدراسة', kicker:'ما الذي لا تدّعيه الدراسة؟', notes:'وضح حدود التعميم: عينة قصدية صغيرة من ثمانية خبراء، جلسة تجريبية واحدة، نموذج أولي يعمل عبر الويب، وسياق ميداني محلي. الاحتفاظ قيس من خلال نية الاستمرار لا من خلال سلوك طويل الأمد.', html:'<div class="slide-card">\n<div class="eyebrow">18 • الحدود</div><h2>قوة الاستنتاج مرتبطة بحدود التصميم</h2>\n<div class="grid-2">\n<div class="stack">\n<div class="panel warn"><div class="label">العينة</div><h3>صغيرة وقصدية</h3><p class="muted">ثمانية مختصين؛ وليست عينة واسعة من اللاعبين.</p></div>\n<div class="panel"><div class="label">التجربة</div><h3>جلسة واحدة</h3><p class="muted">الاحتفاظ مُمثل بنية الاستمرار بدل قياس احتفاظ سلوكي طويل الأمد.</p></div>\n</div>\n<div class="stack">\n<div class="panel"><div class="label">السياق</div><h3>نموذج ويب وبيئة محلية</h3><p class="muted">التطبيق الميداني تم في سياق تقني داخل المملكة العربية السعودية مع مشاركين مرتبطين بأكاديمية طويق.</p></div>\n<div class="panel soft"><div class="label">التفسير</div><h3>دليل واعد وليس إثباتًا عامًا</h3><p class="muted">النتائج تدعم جدوى التكيف القائم على القواعد في سياق الدراسة، بينما يحتاج التعميم إلى أبحاث إضافية.</p></div>\n</div>\n</div>\n<div class="slide-footer"><span>المصدر: ص 10، 15، 23، 31</span><span class="section-number">19</span></div>\n</div>'
},
{
title:'الخاتمة', kicker:'الإجابة في صورة واحدة', notes:'اختم بالرسالة الأساسية: الواجهة التكيفية القائمة على القواعد استطاعت الاستجابة لأداء اللاعب مع الحفاظ على آلية اللعب، والبحث يذكر تحسنًا في مؤشرات تجربة الاستخدام مقارنة بالواجهة الثابتة.', html:'<div class="slide-card">\n<div class="eyebrow">19 • الخاتمة</div><h2>الواجهة التكيفية تحوّل الواجهة الثابتة إلى طبقة مستجيبة</h2>\n<div class="grid-2">\n<div class="panel soft"><div class="label">إجابة السؤال</div><p class="quote">داخل بيئة النموذج الأولي، وفّرت الواجهة التكيفية القائمة على القواعد تجربة أكثر مرونة واستجابة من الواجهة التقليدية.</p></div>\n<div class="stack">\n<div class="panel"><strong>الآلية</strong><p class="muted">مراقبة الأداء → تطبيق القواعد → تعديل عناصر الواجهة.</p></div>\n<div class="panel"><strong>النتيجة</strong><p class="muted">البحث يذكر انخفاض الأخطاء وزمن المهمة وارتفاع نية الاستمرار في الحالة التكيفية.</p></div>\n<div class="panel good"><strong>الاتجاه</strong><p class="muted">الاستجابة لسلوك اللاعب تمثل اتجاهًا واعدًا في تطوير ألعاب الهاتف المحمول.</p></div>\n</div>\n</div>\n<div class="slide-footer"><span>المصدر: ص 2، 28، 30–31</span><span class="section-number">20</span></div>\n</div>'
},
{
title:'التوصيات', kicker:'من نموذج أولي إلى ممارسة تصميمية أوسع', notes:'قدّم التوصيات كما وردت: تبني الواجهات التكيفية، توسيع عناصر التكيف، الاستفادة من بيانات التفاعل، قياس مؤشرات أخرى، وتعزيز التعاون بين الباحثين والمطورين.', html:'<div class="slide-card">\n<div class="eyebrow">20 • التوصيات</div><h2>توسيع الفكرة من نموذج أولي إلى ممارسة</h2>\n<div class="grid-3">\n<div class="panel"><div class="label">للمطورين</div><h3>تبني مفاهيم الواجهات التكيفية</h3><p class="muted">إدماج الاستجابة لسلوك اللاعب ضمن تصميم ألعاب الهاتف المحمول.</p></div>\n<div class="panel soft"><div class="label">للأنظمة</div><h3>توسيع نطاق التكيف</h3><p class="muted">تطبيق التكيف على عناصر إضافية داخل اللعبة عند الحاجة.</p></div>\n<div class="panel"><div class="label">للتقييم</div><h3>قياس أكثر من السرعة والأخطاء</h3><p class="muted">تشمل القياسات رضا المستخدم والتفاعل والاستمرار.</p></div>\n</div>\n<div class="grid-2">\n<div class="panel"><div class="label">البيانات</div><h3>استخدام بيانات التفاعل لتحسين القواعد</h3><p class="muted">الاستفادة من البيانات الناتجة عن تفاعل اللاعبين لبناء آليات تكيف أكثر دقة.</p></div>\n<div class="panel good"><div class="label">التعاون</div><h3>ربط البحث بالتطوير</h3><p class="muted">تعزيز التعاون بين الباحثين ومطوري الألعاب لتطوير حلول عملية.</p></div>\n</div>\n<div class="slide-footer"><span>المصدر: ص 31</span><span class="section-number">21</span></div>\n</div>'
},
{
title:'الدراسات المستقبلية والمراجع', kicker:'أين يمكن أن يذهب البحث بعد ذلك؟', notes:'اختم بمسارات البحث المستقبلية المذكورة في الرسالة: عينات أكبر، استخدام AI/ML في دراسات لاحقة، أنواع ألعاب مختلفة، ومقارنة أساليب التكيف. ثم اعرض المراجع الثمانية الأساسية.', html:'<div class="slide-card">\n<div class="grid-2">\n<div>\n<div class="eyebrow">21 • الدراسات المستقبلية</div>\n<h2>من القواعد الصريحة إلى بحث تكيفي أوسع</h2>\n<div class="bullet-list" style="margin-top:18px">\n<div class="bullet">إجراء تجارب على عينات أكبر من اللاعبين وفي بيئات استخدام مختلفة.</div>\n<div class="bullet">تطوير نماذج تكيف تستخدم الذكاء الاصطناعي والتعلم الآلي في الدراسات المستقبلية.</div>\n<div class="bullet">دراسة ألعاب تعليمية واستراتيجية ومتعددة اللاعبين.</div>\n<div class="bullet">مقارنة أساليب التكيف حسب سهولة الاستخدام والرضا والاحتفاظ.</div>\n</div>\n</div>\n<div>\n<div class="eyebrow">المراجع</div>\n<div class="refs">\n<div><b>Chen, Y., Li, X., & Wang, H. (2021).</b> Predicting Player Churn and Customizing Game Experiences Using Performance Data.</div>\n<div><b>Csikszentmihalyi, M. (1990).</b> Flow: The Psychology of Optimal Experience.</div>\n<div><b>Makris, D. (2016).</b> Technical Challenges in Implementing Adaptive User Interfaces at Runtime.</div>\n<div><b>Nielsen, J. (1994).</b> Enhancing the explanatory power of usability heuristics.</div>\n<div><b>Padte, R. (2019).</b> The Effect of Adaptive Textual Feedback on Player Engagement in Endless Runner Games.</div>\n<div><b>Putkonen, A. (2022).</b> Early Player Behavior as a Predictor of Retention in Free-to-Play Mobile Games.</div>\n<div><b>Sweller, J. (1988).</b> Cognitive load during problem solving: Effects on learning.</div>\n<div><b>Tondello, G. F. (2019).</b> Dynamic Personalization of Interactive Systems.</div>\n</div>\n</div>\n</div>\n<div class="callout"><p class="quote">شكرًا لكم — النقاش.</p></div>\n<div class="slide-footer"><span>المصدر: ص 31–32</span><span class="section-number">22</span></div>\n</div>'
}
];

const stage = document.getElementById("stage");
const counter = document.getElementById("counter");
const slideTitle = document.getElementById("slideTitle");
const progressBar = document.getElementById("progressBar");
const notesPanel = document.getElementById("notesPanel");
const notesBody = document.getElementById("notesBody");
const prevBtn = document.getElementById("prevBtn");
const nextBtn = document.getElementById("nextBtn");
const notesToggle = document.getElementById("notesToggle");
const notesClose = document.getElementById("notesClose");
const fullscreenBtn = document.getElementById("fullscreenBtn");

let index = 0;

slides.forEach((slide, i) => {
  const el = document.createElement("section");
  el.className = `slide ${i === 0 ? "active" : ""}`;
  el.setAttribute("role", "group");
  el.setAttribute("aria-roledescription", "شريحة");
  el.setAttribute("aria-label", `الشريحة ${i + 1} من ${slides.length}: ${slide.title}`);
  el.innerHTML = slide.html;
  stage.appendChild(el);
});
const slideEls = [...document.querySelectorAll(".slide")];

function updateNotes() {
  const s = slides[index];
  const next = index < slides.length - 1 ? `انتقل إلى «${slides[index + 1].title}» بربط النقطة الحالية بالسؤال التالي في منطق الدراسة.` : "اختم المناقشة وافتح باب الأسئلة.";
  notesBody.innerHTML = `
    <div class="note-block"><div class="note-label">ماذا أقول؟</div><div>${escapeHtml(s.notes).replace(/\n/g,"<br>")}</div></div>
    <div class="note-block"><div class="note-label">الانتقال</div><div>${escapeHtml(next)}</div></div>`;
}
function escapeHtml(s){ return s.replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c])); }
function render() {
  slideEls.forEach((el,i)=>{ el.classList.toggle("active",i===index); el.setAttribute("aria-hidden",i===index?"false":"true"); });
  const n=index+1;
  counter.textContent=`${String(n).padStart(2,"0")} / ${String(slides.length).padStart(2,"0")}`;
  slideTitle.textContent=slides[index].title;
  progressBar.style.width=`${(n/slides.length)*100}%`;
  prevBtn.disabled=index===0; nextBtn.disabled=index===slides.length-1;
  updateNotes();
}
function go(delta){ index=Math.max(0,Math.min(slides.length-1,index+delta)); render(); }
function goTo(target){ index=Math.max(0,Math.min(slides.length-1,target)); render(); }
function toggleNotes(force){
  const open=typeof force==="boolean"?force:!notesPanel.classList.contains("open");
  notesPanel.classList.toggle("open",open); notesPanel.setAttribute("aria-hidden",String(!open));
}
async function toggleFullscreen(){
  try{
    if(!document.fullscreenElement) await document.documentElement.requestFullscreen();
    else await document.exitFullscreen();
  }catch(e){}
}
prevBtn.addEventListener("click",()=>go(-1));
nextBtn.addEventListener("click",()=>go(1));
notesToggle.addEventListener("click",()=>toggleNotes());
notesClose.addEventListener("click",()=>toggleNotes(false));
fullscreenBtn.addEventListener("click",toggleFullscreen);
document.addEventListener("keydown",e=>{
  const k=e.key;
  if(["ArrowRight","ArrowDown"," ","PageDown"].includes(k)){e.preventDefault();go(1);}
  if(["ArrowLeft","ArrowUp","PageUp"].includes(k)){e.preventDefault();go(-1);}
  if(k==="Home"){e.preventDefault();goTo(0);}
  if(k==="End"){e.preventDefault();goTo(slides.length-1);}
  if(k.toLowerCase()==="f"){e.preventDefault();toggleFullscreen();}
  if(k.toLowerCase()==="n"){e.preventDefault();toggleNotes();}
  if(k==="Escape"&&notesPanel.classList.contains("open")) toggleNotes(false);
});
let touchX=null;
stage.addEventListener("touchstart",e=>{touchX=e.changedTouches[0].clientX;},{passive:true});
stage.addEventListener("touchend",e=>{if(touchX===null)return;const dx=e.changedTouches[0].clientX-touchX;if(Math.abs(dx)>48)go(dx<0?1:-1);touchX=null;});
render();
